language: java
jdk:
 - openjdk8   
addons:
  sonarcloud:
    organization: "unimibsoftengcourse2021"
    token:
      secure: "1f9bc965adad64f48ce04e625959b7486e4a0235" # encrypted value of your token

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar